/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("WorkScheduleRuleListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheWorkScheduleRuleList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheWorkScheduleRuleList.onFilterBar().iCheckFilterField("AZP-ID");
            Then.onTheWorkScheduleRuleList.onFilterBar().iCheckFilterField("PS-Gruppierung");
            Then.onTheWorkScheduleRuleList.onFilterBar().iCheckFilterField("Feiertagskalender");
            Then.onTheWorkScheduleRuleList.onFilterBar().iCheckFilterField("Gültig ab");
            Then.onTheWorkScheduleRuleList.onFilterBar().iCheckFilterField("Status");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheWorkScheduleRuleList.onTable().iCheckColumns(undefined, {"RuleId":{"header":"AZP-ID"},"Description":{"header":"Bezeichnung"},"AvgWeekHours":{"header":"Ø Woche (h)"},"HolidayCalendarId":{"header":"Feiertagskalender"},"ValidFrom":{"header":"Gültig ab"},"Status":{"header":"Status"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheWorkScheduleRuleList.onFilterBar().iExecuteSearch();
            
            Then.onTheWorkScheduleRuleList.onTable().iCheckRows();

            When.onTheWorkScheduleRuleList.onTable().iPressRow(0);
            Then.onTheWorkScheduleRuleObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});