/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("WorkScheduleRuleObjectPageObjectPage journey");

        opaTest("Navigate to WorkScheduleRuleObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheWorkScheduleRuleList.onFilterBar().iExecuteSearch();

            Then.onTheWorkScheduleRuleList.onTable().iCheckRows();
            When.onTheWorkScheduleRuleList.onTable().iPressRow(0);

            Then.onTheWorkScheduleRuleObjectPage.iSeeThisPage();
        });

        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onTheWorkScheduleRuleObjectPage.onHeader().iCheckHeaderFacet({ facetId: "DataPoint::Status" });
            Then.onTheWorkScheduleRuleObjectPage.onHeader().iCheckHeaderFacet({ facetId: "DataPoint::AvgWeek" });
        });

        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheWorkScheduleRuleObjectPage.iCheckNumberOfSections(6);
            When.onTheWorkScheduleRuleObjectPage.iPressSectionIconTabFilterButton("GeneralInformation");
            Then.onTheWorkScheduleRuleObjectPage.iCheckSection({ section: "GeneralInformation" });
            Then.onTheWorkScheduleRuleObjectPage.onForm({ section: "GeneralInformation" }).iCheckField({ property: "RuleId" });
            Then.onTheWorkScheduleRuleObjectPage.onForm({ section: "GeneralInformation" }).iCheckField({ property: "Description" });
            Then.onTheWorkScheduleRuleObjectPage.onForm({ section: "GeneralInformation" }).iCheckField({ property: "HolidayCalendarId" });
            Then.onTheWorkScheduleRuleObjectPage.onForm({ section: "GeneralInformation" }).iCheckField({ property: "PsGrouping" });
            Then.onTheWorkScheduleRuleObjectPage.onForm({ section: "GeneralInformation" }).iCheckField({ property: "EsGrouping" });
            Then.onTheWorkScheduleRuleObjectPage.onForm({ section: "GeneralInformation" }).iCheckField({ property: "DwsGrouping" });
            Then.onTheWorkScheduleRuleObjectPage.onForm({ section: "GeneralInformation" }).iCheckField({ property: "PeriodId" });
            Then.onTheWorkScheduleRuleObjectPage.onForm({ section: "GeneralInformation" }).iCheckField({ property: "ValidFrom" });
            Then.onTheWorkScheduleRuleObjectPage.onForm({ section: "GeneralInformation" }).iCheckField({ property: "ValidTo" });
            Then.onTheWorkScheduleRuleObjectPage.onForm({ section: "GeneralInformation" }).iCheckField({ property: "Status" });
            When.onTheWorkScheduleRuleObjectPage.iPressSectionIconTabFilterButton("Averages");
            Then.onTheWorkScheduleRuleObjectPage.iCheckSection({ section: "Averages" });
            Then.onTheWorkScheduleRuleObjectPage.onForm({ section: "Averages" }).iCheckField({ property: "AvgDayHours" });
            Then.onTheWorkScheduleRuleObjectPage.onForm({ section: "Averages" }).iCheckField({ property: "AvgWeekHours" });
            Then.onTheWorkScheduleRuleObjectPage.onForm({ section: "Averages" }).iCheckField({ property: "AvgMonthHours" });
            Then.onTheWorkScheduleRuleObjectPage.onForm({ section: "Averages" }).iCheckField({ property: "AvgYearHours" });
            Then.onTheWorkScheduleRuleObjectPage.onForm({ section: "Averages" }).iCheckField({ property: "WorkdaysPerWeek" });
            When.onTheWorkScheduleRuleObjectPage.iPressSectionIconTabFilterButton("WeekPattern");
            Then.onTheWorkScheduleRuleObjectPage.iCheckSection({ section: "WeekPattern" });
            When.onTheWorkScheduleRuleObjectPage.iPressSectionIconTabFilterButton("DailySchedules");
            Then.onTheWorkScheduleRuleObjectPage.iCheckSection({ section: "DailySchedules" });
            When.onTheWorkScheduleRuleObjectPage.iPressSectionIconTabFilterButton("BreakSchedules");
            Then.onTheWorkScheduleRuleObjectPage.iCheckSection({ section: "BreakSchedules" });
            When.onTheWorkScheduleRuleObjectPage.iPressSectionIconTabFilterButton("Assignments");
            Then.onTheWorkScheduleRuleObjectPage.iCheckSection({ section: "Assignments" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});